logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: ${POSTGRESQL_R2DBC_URL}  # r2dbc:postgresql://localhost:5432/books_database
    username: book
    password: book